language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"

install:
    - python setup.py --quiet install

script:
    - ./test.bash

after_success:
    - pip install --quiet coverage
    - make coverage
    - pip install --quiet coveralls
    - coveralls
